package com.example.pokedex.models

data class PokemonEntry(
    val pokemonName: String,
    val imageUrl: String,
    val number: Int
)

/*
val entries : List<PokemonEntry> = listOf(
    PokemonEntry("Bulbasaur",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",1),
    PokemonEntry("Ivysaur",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",2),
    PokemonEntry("Venusaur",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",3),
    PokemonEntry("Charmander",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",4),
    PokemonEntry("Charmeleon",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",5),
    PokemonEntry("Charizard",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",6),
    PokemonEntry("Squirtle",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",7),
    PokemonEntry("Warortle",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",8),
    PokemonEntry("Blastoise",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",9),
    PokemonEntry("Caterpie",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",10),
    PokemonEntry("Metapod",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",11),
    PokemonEntry("Butterfree",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",12),
    PokemonEntry("Weedle",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",13),
    PokemonEntry("Kakuna",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",14),
    PokemonEntry("Beedrill",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",15),
    PokemonEntry("Pidgey",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",16),
    PokemonEntry("Pidgeotto",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",17),
    PokemonEntry("Pidgeot",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",18),
    PokemonEntry("Rattata",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",19),
    PokemonEntry("Raticate",
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",20),
)*/
